apiVersion: v1
data:
  alert-rules.yml: |
    groups:
    - name: nodes.rules
      rules:
      # Alert for any instance that is unreachable for >5 minutes.
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes." 
    - name: kubernetes.rules
      rules:
      - alert: TooManyPodsOnKubernetesNode
        expr: kubelet_running_pod_count > 15
        labels:
          severity: warning
        annotations:
          description: '`{{ $value }}` running pods on Host `{{ $labels.instance }}`. '
          summary: '`{{ $value }}` running pods on Host `{{ $labels.instance }}`'

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertrules-configmap
  namespace: monitoring
