apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: lolspider/prometheus:v2.2.1
        args:
          - '--storage.tsdb.retention=24h'
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--query.max-concurrency=40'
          - '--query.timeout=30s'
        ports:
        - name: webui
          containerPort: 9090
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus

      volumes:
      - name: config-volume
        configMap:
          name: prometheus-configmap
